;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        crux-move-beginning-of-line
        helm-recentf
        ))

(setq mc/cmds-to-run-once
      '(
        js2-mode-show-node
        mouse-set-region
        ))
